# Generated by Django 3.1.5 on 2021-01-19 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_count', models.IntegerField(verbose_name='Количество шагов')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_balance', models.IntegerField(verbose_name='Баланс производителя')),
                ('broker_balance', models.IntegerField(verbose_name='Баланс маклера')),
                ('crow_balance', models.IntegerField(verbose_name='Баланс короны')),
                ('transaction_limit', models.IntegerField(verbose_name='Лимит сделки')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_num', models.IntegerField(blank=True, default='', verbose_name='Игровой шаг')),
                ('step_time', models.IntegerField(blank=True, default='', verbose_name='Время шага')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.game')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='step',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.step'),
        ),
    ]
