# Generated by Django 3.1.5 on 2021-01-23 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='production',
            options={'verbose_name': 'Запрос на производство', 'verbose_name_plural': 'Запросы на производство'},
        ),
        migrations.AlterField(
            model_name='production',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production', to='core.player'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_b', to='core.player'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_m', to='core.player'),
        ),
    ]
