# Generated by Django 3.1.5 on 2021-01-19 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210119_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesetting',
            name='game',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.game', verbose_name='Игра'),
        ),
    ]
