# Generated by Django 3.1.5 on 2021-01-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210123_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
