# Generated by Django 3.1.5 on 2021-01-23 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210123_2125'),
        ('core', '0002_auto_20210124_0022'),
    ]

    operations = [
    ]
