# Generated by Django 3.1.5 on 2021-01-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20210123_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(blank=True, choices=[('broker', 'Маклер'), ('manufacturer', 'Производитель')], default='', max_length=20, verbose_name='Игровая роль'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='billet_price',
            field=models.IntegerField(verbose_name='Цена за заготовку'),
        ),
    ]
