# Generated by Django 3.1.5 on 2021-01-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20210123_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='turn_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='crown_balance',
            field=models.IntegerField(default=12000, verbose_name='Баланс Короны'),
        ),
        migrations.AlterField(
            model_name='state',
            name='game_state',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='billet_price',
            field=models.IntegerField(verbose_name='Цена за заготовку'),
        ),
    ]
