# Generated by Django 3.1.5 on 2021-01-25 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210125_1017'),
        ('core', '0005_auto_20210125_1240'),
    ]

    operations = [
    ]
