# Generated by Django 3.1.5 on 2021-01-19 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210119_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='game',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='core.game', verbose_name='Игра'),
        ),
    ]
