# Generated by Django 3.1.5 on 2021-01-25 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20210125_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='is_bankrupt',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='production',
            name='manufacturer',
            field=models.ForeignKey(limit_choices_to={'role': 'manufacturer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production', to='core.player'),
        ),
        migrations.AlterField(
            model_name='session',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('Created', 'Сессия создана'), ('Filled', 'Сессия заполнена')], default='Created', max_length=100, verbose_name='Статус сессии'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='broker',
            field=models.ForeignKey(limit_choices_to={'role': 'broker'}, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_b', to='core.player'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='manufacturer',
            field=models.ForeignKey(limit_choices_to={'role': 'manufacturer'}, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_m', to='core.player'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='billets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='player',
            field=models.ForeignKey(limit_choices_to={'role': 'manufacturer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse', to='core.player'),
        ),
    ]
