# Generated by Django 3.1.5 on 2021-01-26 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userwebsocket'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.session', verbose_name='Сессия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turn',
            name='turn_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gamesetting',
            name='broker_balance',
            field=models.PositiveIntegerField(verbose_name='Баланс маклера'),
        ),
        migrations.AlterField(
            model_name='gamesetting',
            name='crown_balance',
            field=models.PositiveIntegerField(verbose_name='Баланс короны'),
        ),
        migrations.AlterField(
            model_name='gamesetting',
            name='manufacturer_balance',
            field=models.PositiveIntegerField(verbose_name='Баланс производителя'),
        ),
        migrations.AlterField(
            model_name='gamesetting',
            name='transaction_limit',
            field=models.PositiveIntegerField(verbose_name='Лимит сделки'),
        ),
        migrations.AlterField(
            model_name='production',
            name='billets_produced',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='crown_balance',
            field=models.PositiveIntegerField(default=12000, verbose_name='Баланс Короны'),
        ),
        migrations.AlterField(
            model_name='session',
            name='turn_count',
            field=models.PositiveIntegerField(verbose_name='Количество игровых ходов'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='billet_price',
            field=models.PositiveIntegerField(verbose_name='Цена за заготовку'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='number_of_billets',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='turn',
            name='turn_time',
            field=models.PositiveIntegerField(blank=True, default='', verbose_name='Время хода'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='billets',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
