# Generated by Django 3.1.5 on 2021-01-19 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210119_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesetting',
            name='game',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='game', to='core.game', verbose_name='Игра'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
