# Generated by Django 3.1.5 on 2021-01-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210119_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('M', 'Маклер'), ('P', 'Производитель')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
