# Generated by Django 3.1.5 on 2021-01-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210119_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='step',
            field=models.ManyToManyField(related_name='gamestep', to='core.Step'),
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='step',
        ),
        migrations.AddField(
            model_name='transaction',
            name='step',
            field=models.ManyToManyField(related_name='step', to='core.Step'),
        ),
    ]
