# Generated by Django 3.1.5 on 2021-01-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210121_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='step',
        ),
        migrations.AddField(
            model_name='step',
            name='transaction',
            field=models.ManyToManyField(related_name='gamestep', to='core.Transaction'),
        ),
    ]
