# Generated by Django 3.1.5 on 2021-01-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210121_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_start',
            field=models.BooleanField(default=False, verbose_name='Старт игры'),
        ),
        migrations.AddField(
            model_name='game',
            name='game_status',
            field=models.BooleanField(default=True, verbose_name='Статус игры'),
        ),
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя игры'),
        ),
    ]
